/* Run from the Front repo: node tools/gen-terms.js [--check] [--require-commits].
   Add legal/terms/vN.json for each revision; never edit a committed snapshot.
   Git supplies the introducing commit, so no self-referential SHA is needed.
   The deploy runs this in its detached worktree before copying site/. */
const fs = require('fs');
const { execFileSync } = require('child_process');

let gitRoot = '.';
function git(args) {
  try { return execFileSync('git', ['-C', gitRoot, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], env: Object.fromEntries(Object.entries(process.env).filter(([key]) => !key.startsWith('GIT_'))) }).trim(); }
  catch { return null; }
}

function generate({ check = false, requireCommits = false, repository = '.' } = {}) {
  gitRoot = repository;
  const shallow = git(['rev-parse', '--is-shallow-repository']) === 'true';
  if (shallow && requireCommits) throw Error('Full Git history is required to resolve introducing commits; fetch --unshallow first');
  const dicts = require('./dicts.js').load();
  const files = fs.readdirSync('legal/terms').filter(f => /^v[1-9]\d*\.json$/.test(f));
  const revisions = files.map(file => {
    const source = `legal/terms/${file}`;
    const raw = fs.readFileSync(source, 'utf8');
    const rev = JSON.parse(raw);
    if (file !== `v${rev.version}.json` || !/^\d{4}-\d{2}-\d{2}$/.test(rev.date) ||
        new Date(rev.date).toISOString().slice(0, 10) !== rev.date) throw Error(`${source}: invalid version/date`);
    for (const lang of ['en', 'pt']) {
      if (!rev.summary?.[lang] || !rev.text?.[lang]) throw Error(`${source}: missing ${lang}`);
      if (Object.keys(rev.text[lang]).sort().join() !== Object.keys(rev.text.en).sort().join())
        throw Error(`${source}: language keys differ`);
      if (Object.values(rev.text[lang]).some(value => typeof value !== 'string' || !value.trim()))
        throw Error(`${source}: empty or invalid text`);
    }
    const commits = shallow ? null : git(['log', '--diff-filter=A', '--format=%H', '--', source]);
    const commit = commits?.split('\n').at(-1) || null;
    if (commit) {
      const original = git(['show', `${commit}:${source}`]);
      if (original !== raw.trim()) throw Error(`${source}: published snapshot changed; add a revision instead`);
    } else if (requireCommits) {
      throw Error(`${source}: no introducing Git commit; commit the snapshot before publishing`);
    }
    return { ...rev, commit };
  }).sort((a, b) => a.version - b.version);
  if (!revisions.length) throw Error('No terms revisions');
  revisions.forEach((rev, i) => {
    if (rev.version !== i + 1) throw Error('Terms versions must be consecutive from 1');
    if (i && rev.date < revisions[i - 1].date) throw Error('Terms dates must be chronological');
  });
  // A revision cannot disappear from the record in a later working tree.
  const tracked = shallow ? git(['ls-tree', '-r', '--name-only', 'HEAD', '--', 'legal/terms'])
    : git(['log', '--diff-filter=A', '--name-only', '--format=', '--', 'legal/terms']);
  for (const source of (tracked || '').split('\n').filter(f => /\/v\d+\.json$/.test(f))) {
    if (!fs.existsSync(source)) throw Error(`${source}: committed revision was removed`);
  }
  const latest = revisions.at(-1);
  for (const [lang, dict] of Object.entries(dicts)) {
    const expected = latest.text[lang] || latest.text.en;
    const live = Object.fromEntries(Object.entries(dict).filter(([k]) =>
      k.startsWith('tos.doc_') || ['tos.title', 'tos.eyebrow', 'tos.h1', 'tos.lede', 'tos.updated'].includes(k)));
    if (JSON.stringify(Object.entries(live).sort()) !== JSON.stringify(Object.entries(expected).sort()))
      throw Error(`${lang}: terms snapshot and live dictionary differ; add a revision and rebuild i18n`);
  }
  const log = revisions.map(({ text, ...metadata }) => metadata);
  const texts = Object.fromEntries(revisions.map(rev => [rev.version, rev.text]));
  const markdown = s => s.replace(/<b>([\s\S]*?)<\/b>/g, '**$1**')
    .replace(/<a href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g, (_, href, label) =>
      `[${label}](${href.startsWith('/') ? 'https://steamprofiler.org' + href : href})`);
  const document = [
    '# Terms of Service / Terms of Use',
    '',
    '<!-- Generated from legal/terms/vN.json by tools/gen-terms.js. -->',
    '',
    `v${latest.version} · ${latest.date}`,
    '',
    '[Página publicada / Published page](https://steamprofiler.org/terms) · [Histórico com commits Git / Git-linked history](https://steamprofiler.org/terms/history)',
    '',
  ];
  for (const lang of ['pt', 'en']) {
    const text = latest.text[lang];
    document.push(`## ${lang === 'pt' ? 'Português' : 'English'}`, '', text['tos.lede'], '');
    for (const key of Object.keys(text).filter(k => k.endsWith('_head')).sort()) {
      document.push(`### ${text[key]}`, '', markdown(text[key.replace(/_head$/, '_body')]), '');
    }
  }
  const outputs = {
    'site/terms-log.js': `/* Generated by tools/gen-terms.js. Commit is null only for an unpublished draft. */\nconst TERMS_LOG = ${JSON.stringify(log, null, 2)};\n`,
    'site/terms-text.js': `/* Generated from immutable legal/terms/vN.json snapshots. */\nconst TERMS_TEXT = ${JSON.stringify(texts, null, 2)};\n`,
    'TERMS.md': document.join('\n'),
  };
  let pageCommit = latest.commit;
  for (const [file, content] of Object.entries(outputs)) {
    if (check) {
      const actual = fs.readFileSync(file, 'utf8');
      // Before generation after a commit, null is allowed; a wrong SHA never is.
      if (file.endsWith('terms-log.js')) {
        const vm = require('vm');
        const ctx = {}; vm.createContext(ctx);
        vm.runInContext(actual + ';globalThis.log = TERMS_LOG;', ctx);
        if (ctx.log.length !== log.length) throw Error(`${file}: revision count differs`);
        for (let i = 0; i < log.length; i++) {
          const expected = { ...log[i], commit: ctx.log[i].commit === null && !requireCommits ? null : log[i].commit };
          if (JSON.stringify(ctx.log[i]) !== JSON.stringify(expected)) throw Error(`${file}: metadata or commit differs`);
        }
        pageCommit = ctx.log.at(-1).commit;
      } else if (actual !== content) throw Error(`${file}: archive differs; run node tools/gen-terms.js`);
    } else fs.writeFileSync(file, content);
  }
  const pageFile = 'site/terms.html';
  const page = fs.readFileSync(pageFile, 'utf8');
  const commitLink = pageCommit
    ? `<a id="tos-commit" href="https://github.com/GustavoHSCruz/SteamProfiler.Front/commit/${pageCommit}" rel="noopener noreferrer" target="_blank">${pageCommit.slice(0, 7)}</a>`
    : '<a id="tos-commit" hidden rel="noopener noreferrer" target="_blank"></a>';
  const rendered = page
    .replace(/<span id="tos-version">[^<]*<\/span>/, `<span id="tos-version">v${latest.version}</span>`)
    .replace(/<time id="tos-date"[^>]*>[^<]*<\/time>/, `<time id="tos-date" datetime="${latest.date}">${latest.date}</time>`)
    .replace(/"dateModified":"[^"]*"/, `"dateModified":"${latest.date}"`)
    .replace(/<a id="tos-commit"[^>]*>[\s\S]*?<\/a>/, commitLink)
    .replace(/<p class="form-note" id="tos-draft"(?: hidden)?/, `<p class="form-note" id="tos-draft"${pageCommit ? ' hidden' : ''}`);
  if (check && page !== rendered) throw Error(`${pageFile}: revision metadata differs; run node tools/gen-terms.js`);
  if (!check) fs.writeFileSync(pageFile, rendered);
  console.log(`terms ok: ${revisions.length} revision(s), ${Object.keys(latest.text.en).length} keys, ${log.filter(r => r.commit).length} Git commit(s)`);
  return revisions;
}

module.exports = { generate };
if (require.main === module) {
  const rootIndex = process.argv.indexOf('--git-root');
  try {
    if (rootIndex !== -1 && !process.argv[rootIndex + 1]) throw Error('--git-root requires a repository path');
    generate({ check: process.argv.includes('--check'), requireCommits: process.argv.includes('--require-commits'), repository: rootIndex === -1 ? '.' : process.argv[rootIndex + 1] });
  }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
